version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: kanban-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: ./backend
  #   container_name: kanban-backend
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ./backend/.env
  #   restart: unless-stopped

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: kanban-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  kanban-frontend:
    build:
      context: ./frontend
    depends_on:
      - backend-dev
    ports:
      - "3000:80"

volumes:
  pg_data:
